### ISSUE TITLE
com.google.android.exoplayer2.ExoPlaybackException: Source error

### ISSUE THREAD

**Issue by tudosxxx** [the-best-is-best/tbib_cahched_video_player#2]
I can use videoplayer,

change to tbib_cahched_video_player  is error,

E/ExoPlayerImplInternal(17482): Playback error
E/ExoPlayerImplInternal(17482):   com.google.android.exoplayer2.ExoPlaybackException: Source error
E/ExoPlayerImplInternal(17482):       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:554)
E/ExoPlayerImplInternal(17482):       at android.os.Handler.dispatchMessage(Handler.java:102)
E/ExoPlayerImplInternal(17482):       at android.os.Looper.loop(Looper.java:214)
E/ExoPlayerImplInternal(17482):       at android.os.HandlerThread.run(HandlerThread.java:65)
E/ExoPlayerImplInternal(17482):   Caused by: com.google.android.exoplayer2.upstream.HttpDataSource$HttpDataSourceException: Unable to connect
E/ExoPlayerImplInternal(17482):       at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:309)
E/ExoPlayerImplInternal(17482):       at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:199)
E/ExoPlayerImplInternal(17482):       at com.google.android.exoplayer2.upstream.TeeDataSource.open(TeeDataSource.java:54)
E/ExoPlayerImplInternal(17482):       at com.google.android.exoplayer2.upstream.cache.CacheDataSource.openNextSource(CacheDataSource.java:764)
E/ExoPlayerImplInternal(17482):       at com.google.android.exoplayer2.upstream.cache.CacheDataSource.open(CacheDataSource.java:579)
E/ExoPlayerImplInternal(17482):       at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:84)
E/ExoPlayerImplInternal(17482):       at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:1013)
E/ExoPlayerImplInternal(17482):       at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:415)
E/ExoPlayerImplInternal(17482):       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/ExoPlayerImplInternal(17482):       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/ExoPlayerImplInternal(17482):       at java.lang.Thread.run(Thread.java:764)
E/ExoPlayerImplInternal(17482):   Caused by: java.io.IOException: Cleartext HTTP traffic to cdn.alphaandomega.top not permitted
E/ExoPlayerImplInternal(17482):       at com.android.okhttp.HttpHandler$CleartextURLFilter.checkURLPermitted(HttpHandler.java:115)
E/ExoPlayerImplInternal(17482):       at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:467)
E/ExoPlayerImplInternal(17482):       at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:127)
E/ExoPlayerImplInternal(17482):       at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.makeConnection(DefaultHttpDataSource.java:589)
E/ExoPlayerImplInternal(17482):       at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.makeConnection(DefaultHttpDataSource.java:493)
E/ExoPlayerImplInternal(17482):       at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:307)
E/ExoPlayerImplInternal(17482):       ... 10 more
E/flutter (17482): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: PlatformException(VideoError, Video player had error com.google.android.exoplayer2.ExoPlaybackException: Source error, null, null)
E/flutter (17482): 
W/JavaBinder(17482): BinderProxy is being destroyed but the application did not call unlinkToDeath to unlink all of its death recipients beforehand.  Releasing leaked death recipient: com.google.android.play.core.internal.ai

**Comment by tudosxxx** [comment]
If the video is too long or too big, there will be no sound when playing the video

**Comment by tudosxxx** [comment]
in Android

**Comment by the-best-is-best** [comment]
This plugin is disconnected
